// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yogbwckwkbqcltaamevn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZ2J3Y2t3a2JxY2x0YWFtZXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzQ3MzEsImV4cCI6MjA3MzcxMDczMX0.BOg2K3DAP5-xbj6zEAqZlgx0RA0httBOWyClcQE3ryo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});